name: Run CI

on:
  push:
  pull_request:
    branches:
      - main # Or your default branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        # python-version:
        #   - "3.10"
        #   - "3.11"
        #   - "3.12"
        #   - "3.13"
    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Chicago"
          timezoneMacos: "America/Chicago"
          timezoneWindows: "Central Standard Time"

      - uses: actions/checkout@v4
        with:
          submodules: true

      # - name: Install Python dependencies
      #   if: contains( matrix.os, 'ubuntu')
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install hatch
